[global]
# keystore path，absolute path, or current path
keystore="keystore.json"
# The password can be empty,but it can't be wrong. If it is empty，enter the password manually when required.
# The password does not support plaintext. Run a subcommand password to generate AES ciphertext
# Ciphertext is machine related
password = "1234561"
# Suggest that block_number_by_estimation is true, if it is true, block_creating_seconds is more important
# True will work a little faster，
block_number_by_estimation = false
router_contract = ""
# start_with_block, You can only change the value to a larger value, but cannot change it to a smaller value.
# To change the value to a smaller value, you need to delete the database content
start_with_block = 1
# How many blocks are synchronized at one time? This value can only be between 1 and 20, preferably less than 10
# nan will set to 1
block_number_limit_once = 5

[src_chain]
#The name doesn't matter, it only shows up in the log
name = "Ethereum test net"
chain_id = 10
block_creating_seconds = 15
rpc_url = "http://119.8.165.158:8545"
stable_block = 10
router_contract_address = ""

[dst_chain]
##The name doesn't matter, it only shows up in the log
name = "map_chain_test"
chain_id = 211
block_creating_seconds = 6
rpc_url = "http://119.8.165.158:7445"
stable_block = 10
relayer_contract_address = "0x00000000000052656c6179657241646472657373"
header_store_contract_address = "0x000068656164657273746F726541646472657373"
router_contract_address = ""

